### ISSUE TITLE
Authorizations in service results in crashing

### ISSUE THREAD

**Issue by timoschuetz** [SAP-samples/cloud-cap-samples#21]
While trying a few thing on the documentation on cap.cloud.sap page I created a new project using the "Getting Started in a Nutshell". I was able to push the project to my trial account with the documentation. As the documentation is somewhat unclear on a few points I have uploaded my code to Github - Maybe there is an issue in the structure of my project or my files? It states that there is "No service matches xsuaa", although I have created a service file and definition in the default-env.json analogous to the sample file.

Code: https://github.com/timoschuetz/capm-auth

I deploy the service with 
`
cds build/all 
cf push -f gen/srv --random-route 
`

Now I am planning to add authorization to the service, but it is always failing - these are the logs:

`2020-01-08T14:05:33.181+0000 [APP/PROC/WEB/0] ERR     at getCredentialsFromXsEnv (/home/vcap/deps/0/node_modules/@sap/cds-services/lib/util/xsenv.js:41:20)
2020-01-08T14:05:33.181+0000 [APP/PROC/WEB/0] ERR     at _jwt (/home/vcap/deps/0/node_modules/@sap/cds-services/lib/adapter/auth/passport.js:47:53)
2020-01-08T14:05:33.181+0000 [APP/PROC/WEB/0] ERR     at _getOneStrategyByName (/home/vcap/deps/0/node_modules/@sap/cds-services/lib/adapter/auth/passport.js:85:80)
2020-01-08T14:05:33.182+0000 [APP/PROC/WEB/0] ERR     at _getStrategy (/home/vcap/deps/0/node_modules/@sap/cds-services/lib/adapter/auth/passport.js:121:10)
2020-01-08T14:05:33.182+0000 [APP/PROC/WEB/0] ERR     at _autoDetectStrategy (/home/vcap/deps/0/node_modules/@sap/cds-services/lib/adapter/auth/passport.js:168:10)
2020-01-08T14:05:33.182+0000 [APP/PROC/WEB/0] ERR     at _getAuthConfig (/home/vcap/deps/0/node_modules/@sap/cds-services/lib/adapter/auth/passport.js:206:40)
2020-01-08T14:05:33.182+0000 [APP/PROC/WEB/0] ERR     at passport (/home/vcap/deps/0/node_modules/@sap/cds-services/lib/adapter/auth/passport.js:252:22)
2020-01-08T14:05:33.182+0000 [APP/PROC/WEB/0] ERR     at Function.passport (/home/vcap/deps/0/node_modules/@sap/cds-services/lib/index.js:22:46)
2020-01-08T14:05:33.182+0000 [APP/PROC/WEB/0] ERR   jse_shortmsg: 'No service matches xsuaa',
2020-01-08T14:05:33.182+0000 [APP/PROC/WEB/0] ERR   jse_info: {},
2020-01-08T14:05:33.182+0000 [APP/PROC/WEB/0] ERR   message: 'No service matches xsuaa' }
2020-01-08T14:05:33.422+0000 [APP/PROC/WEB/0] OUT Exit status 143`

**Comment by chgeo** [comment]
Same as OSS issue 0020751294 0000013976 2020.
Let's continue there.
