### ISSUE TITLE
How to create a oData V2 service?

### ISSUE THREAD

**Issue by superwangnan** [SAP-samples/cloud-cap-samples#27]
Hi team
as I test, follow most of our tutorial, we will create a oData V4 service by default. Do we have a tutorial to create oData V2 service?
Thanks.

**Comment by chgeo** [comment]
Hi,

this has been asked quite a few times.  Please refer to the online resources, like [here](https://answers.sap.com/questions/12928430/cap-odata-v2-adapter.html) or [here](https://developers.sap.com/tutorials/cap-cloudsdk-2-v2-adapter.html) 
(Google search for 'cap odata v2').

Regards,
Christian

**Comment by superwangnan** [comment]
Hi Chgeo
Thanks for reply. Yes, I found these articles before. But frankly, I don't know to do use it. What's confuse me is: it see need to rewrite the server.js script. but in our cap guide, we use the cds command generate most thing. If I need rewrite the server.js, how can I combine the server.js with generated code? 

Another thing is: how to add java adapter in a java based app?

cap.cloud.sap is great document to show how to quick start the cap project. Do we have any deeper guide for customize the generated code? or if I want to apply cds in my existing java or Node js project, how to do that?

Thanks so much in advanced?

**Comment by superwangnan** [comment]
Hi Chgeo, 
I follow this [guide](https://github.com/gregorwolf/SAP-NPM-API-collection/tree/master/apis/cds-odata-v2-adapter-proxy) and create index.js under srv folder. when I run node srv/index, I got following error:
node srv/index.js
(node:74511) UnhandledPromiseRejectionWarning: Error: Invalid attempt to access '.entities' for service 'db' with no model loaded.
    at _model_get (/Users/i062905/tmp/tmp001/cloud-cap-samples/packages/bookshop/node_modules/@sap/cds/lib/runtime/service-client.js:35:19)
    at Service.get entities [as entities] (/Users/i062905/tmp/tmp001/cloud-cap-samples/packages/bookshop/node_modules/@sap/cds/lib/runtime/service-client.js:16:29)
    at cds.get entities [as entities] (/Users/i062905/tmp/tmp001/cloud-cap-samples/packages/bookshop/node_modules/@sap/cds/lib/cds.js:75:36)
    at Object.<anonymous> (/Users/i062905/tmp/tmp001/cloud-cap-samples/packages/bookshop/gen/srv/srv/cat-service.js:2:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
(node:74511) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:74511) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:74511) UnhandledPromiseRejectionWarning: Error: Invalid attempt to access '.entities' for service 'db' with no model loaded.
    at _model_get (/Users/i062905/tmp/tmp001/cloud-cap-samples/packages/bookshop/node_modules/@sap/cds/lib/runtime/service-client.js:35:19)
    at Service.get entities [as entities] (/Users/i062905/tmp/tmp001/cloud-cap-samples/packages/bookshop/node_modules/@sap/cds/lib/runtime/service-client.js:16:29)
    at cds.get entities [as entities] (/Users/i062905/tmp/tmp001/cloud-cap-samples/packages/bookshop/node_modules/@sap/cds/lib/cds.js:75:36)
    at Object.<anonymous> (/Users/i062905/tmp/tmp001/cloud-cap-samples/packages/bookshop/gen/srv/srv/cat-service.js:2:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
(node:74511) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

I use the bookshop sample from github.

a further question: if this index.js work, is all of cds features ( for example: CDS_ENV  ) will work there?

Thanks.
