### ISSUE TITLE
Fiori preview for bookshop doesnot work

### ISSUE THREAD

**Issue by karthikraov** [SAP-samples/cloud-cap-samples#44]
I am able to run the application, and view the services and the odata output. But when I click on "..in FIori" it opens up a page like below :

![image](https://user-images.githubusercontent.com/6973239/77872454-9e847b80-7264-11ea-828d-4136d04bb244.png)

and I can see the below error in console : 

`Failed to create cache for binding sap.ui.model.odata.v4.ODataListBinding: /Authors - TypeError: Cannot read property '$kind' of undefined
    at Object.wrapChildQueryOptions (https://sapui5.hana.ondemand.com/resources/sap/ui/core/library-preload.js?eval:4172:11259)
    at eval (https://sapui5.hana.ondemand.com/resources/sap/ui/core/library-preload.js?eval:4172:3481)
    at https://sapui5.hana.ondemand.com/resources/sap-ui-core.js:596:173
    at c (https://sapui5.hana.ondemand.com/resources/sap-ui-core.js:591:99)
    at new S (https://sapui5.hana.ondemand.com/resources/sap-ui-core.js:593:773)
    at S.then (https://sapui5.hana.ondemand.com/resources/sap-ui-core.js:596:151)
    at eval (https://sapui5.hana.ondemand.com/resources/sap/ui/core/library-preload.js?eval:4172:3457)
    at Array.map (<anonymous>)
    at Object.fetchResolvedSelect (https://sapui5.hana.ondemand.com/resources/sap/ui/core/library-preload.js?eval:4172:3400)
    at eval (https://sapui5.hana.ondemand.com/resources/sap/ui/core/library-preload.js?eval:3762:413) sap.ui.model.odata.v4.ODataBinding`

**Comment by chgeo** [comment]
Can you make sure you have defined some `UI.LineItems` for your model?  Otherwise Fiori will not show any data.  See the [fiori app](https://github.com/SAP-samples/cloud-cap-samples/blob/master/fiori/app/common.cds#L16-L24) for some examples.
