### ISSUE TITLE
Week 2 Unit 4 - Error during CDS deploy --to sqlite

### ISSUE THREAD

**Issue by reachtomskn** [SAP-samples/cloud-cap-samples#450]
Below internal error happens and package.json file is not updated. 

cds deploy --to sqlite
 > init from db/data/sap.capire.bookshop-Authors.csv
 > init from db/data/sap.capire.bookshop-Books.csv
 > init from db/data/sap.capire.bookshop-Books_texts.csv
 > init from db/data/sap.capire.bookshop-OrderItems.csv
 > init from db/data/sap.capire.bookshop-Orders.csv
 > init from db/data/sap.common-Currencies.csv
 > init from db/data/sap.common-Currencies_texts.csv
/> successfully deployed to ./db.sqlite

[INTERNAL ERROR] TypeError: Cannot set properties of undefined (setting 'db')
    at update_package_json (/extbin/npm/globals/lib/node_modules/@sap/cds-dk/bin/deploy/index.js:117:15)
    at async Object.deploy (/extbin/npm/globals/lib/node_modules/@sap/cds-dk/bin/deploy/index.js:100:27)

**Comment by reachtomskn** [comment]
Closing this issue, as the issue is already raised in SCN : https://answers.sap.com/questions/13809437/error-deploying-to-sqlite-error-update-package-jso.html

**Comment by reachtomskn** [comment]
Closing this issue, as the issue is already raised in SCN : https://answers.sap.com/questions/13809437/error-deploying-to-sqlite-error-update-package-jso.html
