### ISSUE TITLE
mismatch of Db schema and test data

### ISSUE THREAD

**Issue by hitesharora2** [SAP-samples/cloud-cap-samples#57]
there  is some mismatch of declared db schema and test data CSV files leading to error for "No Column found ... "   in Week 1 unit 4 bookshop project

**Comment by chgeo** [comment]
Thanks for reporting this.
Can you add the complete error information?

**Comment by cdssupernova** [comment]
[ERROR] Couldn't find a CDS model for: schema.cds in: /home/user/projects
    at cds.load (/home/user/.node_modules_global/lib/node_modules/@sap/cds-dk/node_modules/@sap/cds/lib/models/load.js:15:39)
    at Object.compile (/home/user/.node_modules_global/lib/node_modules/@sap/cds-dk/node_modules/@sap/cds/bin/compile.js:120:21)
    at Module.exports (/home/user/.node_modules_global/lib/node_modules/@sap/cds-dk/node_modules/@sap/cds/bin/cds.js:44:23)
    at Object.<anonymous> (/home/user/.node_modules_global/lib/node_modules/@sap/cds-dk/bin/cds.js:32:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

**Comment by cdssupernova** [comment]
Looks like this is because of the error at below line:
(Error Msg - Cannot find package module '@sap/cds/common'CDS(file-unknown-package))

using { Currency, managed } from '@sap/cds/common';

In test project structure/setup node_modules folder is missing. In my local system setup it works fine.

**Comment by chgeo** [comment]
> [ERROR] Couldn't find a CDS model for: schema.cds in: /home/user/projects

This looks like you executed the command in the wrong folder.  `cd` inside the `bookshop` folder (or whatever the app root folder is).
