### ISSUE TITLE
Server will crash when query with filter like: $filter=false and age ge 12

### ISSUE THREAD

**Issue by fourmatrix** [SAP-samples/cloud-cap-samples#58]
entity:
```swift
entity Foo : managed {
  key ID: UUID;
  startTime: DateTime;
  name: String;
  age: Integer;
}
```
service:
```swift
service TestService {
   entity Foo as projection on my.Foo;
}
```
query:

[http://localhost:4004/test/Foo?$filter=false](http://localhost:4004/test/Foo?$filter=false)
[http://localhost:4004/test/Foo?$filter=age ge 12](http://localhost:4004/test/Foo?$filter=age%20ge%2012)
[http://localhost:4004/test/Foo?$filter=false or age ge 12](http://localhost:4004/test/Foo?$filter=false%20or%20age%20ge%2012)
query 1 and 2 are right, but 3 with error:
```
[INTERNAL ERROR] TypeError: left is not iterable
at ExpressionToCQN._binary (/node/v10.19.0/lib/node_modules/@sap/cds-dk/node_modules/@sap/cds-services/lib/adapter/odata-v4/odata-to-cqn/ExpressionToCQN.js:259:25)
at ExpressionToCQN.parse (/node/v10.19.0/lib/node_modules/@sap/cds-dk/node_modules/@sap/cds-services/lib/adapter/odata-v4/odata-to-cqn/ExpressionToCQN.js:294:21)
at _filter (/node/v10.19.0/lib/node_modules/@sap/cds-dk/node_modules/@sap/cds-services/lib/adapter/odata-v4/odata-to-cqn/readToCQN.js:42:50)
at readToCQN (/node/v10.19.0/lib/node_modules/@sap/cds-dk/node_modules/@sap/cds-services/lib/adapter/odata-v4/odata-to-cqn/readToCQN.js:243:5)
at odataToCQN (/node/v10.19.0/lib/node_modules/@sap/cds-dk/node_modules/@sap/cds-services/lib/adapter/odata-v4/odata-to-cqn/odataToCQN.js:24:14)
at OdataContext.get (/node/v10.19.0/lib/node_modules/@sap/cds-dk/node_modules/@sap/cds-services/lib/adapter/odata-v4/utils/OdataContext.js:265:23)
at Object.context [as handler] (/node/v10.19.0/lib/node_modules/@sap/cds-dk/node_modules/@sap/cds-services/lib/services/handlers/onRead.js:13:15)
at next (/node/v10.19.0/lib/node_modules/@sap/cds-dk/node_modules/@sap/cds-services/lib/services/hooks/On.js:185:37)
at On._middleware (/node/v10.19.0/lib/node_modules/@sap/cds-dk/node_modules/@sap/cds-services/lib/services/hooks/On.js:214:5)
at Promise (/node/v10.19.0/lib/node_modules/@sap/cds-dk/node_modules/@sap/cds-services/lib/services/hooks/On.js:84:12)
Please report this error.
```

**Comment by chgeo** [comment]
@David-Kunz can you dispatch this?

**Comment by David-Kunz** [comment]
Hi,
Thanks for pointing that out.
I don't understand the filter in
`http://localhost:4004/test/Foo?$filter=false`.
What is this supposed to filter?

Anyway, the server should not crash because of that.

Thanks again and best regards,
David

**Comment by fourmatrix** [comment]
Hi David,  

We call the OData service with SAP UI5 ODataModel, when we add filter like:
`
var timeFilter=new Filter({filters:crossTimeFilter,and:false});
`

In some conditions, it will send request with parameter like ` $filter=false `,  the filter is generated by UI5 automatically, I think it's a valid filter, actually, 
`http://localhost:4004/test/Foo?$filter=false` does not cause problem.


Best regards,
Chenghai

**Comment by David-Kunz** [comment]
Hi,

>> http://localhost:4004/test/Foo?$filter=false does not cause problem.
Yes, but what is it supposed to do? I would expect the server to throw an error for this.

Best regards,
David

**Comment by fourmatrix** [comment]
Hi David,
Add one more condition, for example :
http://localhost:4004/test/Foo?$filter=false or age ge 12

You can get the error.

Best regards,

**Comment by David-Kunz** [comment]
Yes, 
But what's the meaning of `$filter=false or age ge 12`? It doesn't make any sense.

**Comment by David-Kunz** [comment]
Ok.. it will be fixed in the new version. Then we allow `false` which will directly translated to `false` in the SQL where clause. Note: This is not supported on SAP HANA.

**Comment by fourmatrix** [comment]
Hi David,

I don't think `$filter=false or age ge 12`  make any sense,  just found some coding in UI5  will create this query filter, maybe it's a bug,  but it leads to crash, if it's invalid and we don't support this kind of filter, an exception or error would be better, the user will know that there are bugs in his coding.

Best regards

**Comment by Vest** [comment]
**$filter** requires a simple boolean expression, so in theory **$filter=false** should be valid. E.g. this URL works as expected: https://services.odata.org/TripPinRESTierService/People?$filter=false

**Comment by David-Kunz** [comment]
Hi @Vest,

Yes that's true, but it doesn't make any sense to send such requests.

Anyway, we will support those filters in the newest version of `@sap/cds`.

Best regards,
David
